/* ============================================================
   SAFURA LONDON — Product Catalogue
   12 collections × 4 sizes
   ============================================================ */

const SIZES = [
  { label: 'XS', uk: 'UK 6–8',   eu: 'EU 34–36', bust: '80–84 cm',  available: true  },
  { label: 'S',  uk: 'UK 10',    eu: 'EU 38',    bust: '85–89 cm',  available: true  },
  { label: 'M',  uk: 'UK 12–14', eu: 'EU 40–42', bust: '90–96 cm',  available: true  },
  { label: 'L',  uk: 'UK 16',    eu: 'EU 44',    bust: '97–104 cm', available: true  },
];

const COLLECTIONS = [
  {
    id: 1,
    slug: 'al-nur',
    name: 'Al-Nur',
    arabic: 'النور',
    meaning: 'The Light',
    tagline: 'Where darkness meets radiance',
    price: 285,
    color: '#0F0F0F',
    accentColor: '#C9A96E',
    fabric: 'Premium Nida with gold-thread embroidery',
    care: 'Dry clean only',
    origin: 'Handcrafted in London',
    description: 'Al-Nur is our most celebrated design — a masterpiece of restraint and detail. Cut from the finest black Nida fabric, its only adornment is a whisper of hand-stitched gold thread tracing the cuffs and neckline. Timeless. Transformative.',
    details: 'Full-length floor-grazing silhouette with flared sleeves. Concealed zip fastening at neck. Generous cut allowing for modest movement and layering. Exclusive to Safura London.',
    seoDesc: 'Luxury black abaya with gold embroidery. The Al-Nur collection by Safura London — premium Nida fabric, handcrafted in the UK. Available in XS–L.',
    badge: 'Bestseller',
    featured: true,
    sizes: [...SIZES],
  },
  {
    id: 2,
    slug: 'laleh',
    name: 'Laleh',
    arabic: 'لاله',
    meaning: 'Tulip',
    tagline: 'A bloom in perpetual grace',
    price: 195,
    color: '#3D0F1E',
    accentColor: '#E8B4C4',
    fabric: 'Luxury crepe de chine',
    care: 'Gentle hand wash or dry clean',
    origin: 'Handcrafted in London',
    description: 'Laleh honours the tulip — a bloom revered across the Ottoman world as a symbol of divine love and paradise. This deep burgundy abaya drapes with the effortless elegance of falling petals, its crepe de chine fabric catching light like morning dew.',
    details: 'Open-front kimono style with broad sleeves. Satin-lined interior. Available in the signature Laleh burgundy.',
    seoDesc: 'Burgundy crepe de chine abaya by Safura London. The Laleh collection — tulip-inspired modest fashion from the UK.',
    badge: null,
    featured: true,
    sizes: [...SIZES],
  },
  {
    id: 3,
    slug: 'zahra',
    name: 'Zahra',
    arabic: 'زهراء',
    meaning: 'Blossom',
    tagline: 'Ivory purity, enduring grace',
    price: 165,
    color: '#F0E8D5',
    accentColor: '#8B7355',
    fabric: 'Italian viscose georgette',
    care: 'Dry clean recommended',
    origin: 'Handcrafted in London',
    description: 'Zahra captures the luminosity of ivory — pure, timeless, and impossibly elegant. Crafted from Italian georgette that moves like a second breath, this abaya is the choice for weddings, Eid gatherings, and every moment that deserves beauty.',
    details: 'Flowing A-line silhouette with delicate pintuck detail at shoulder. Self-tie belt included. Available in ivory only.',
    seoDesc: 'Ivory luxury abaya by Safura London. Zahra collection in Italian georgette — perfect for weddings and Eid. Free UK delivery.',
    badge: 'New',
    featured: true,
    sizes: [...SIZES],
  },
  {
    id: 4,
    slug: 'yasmin',
    name: 'Yasmin',
    arabic: 'ياسمين',
    meaning: 'Jasmine',
    tagline: 'Night air, floral soul',
    price: 175,
    color: '#12243A',
    accentColor: '#B8CCE0',
    fabric: 'Matte satin with jersey lining',
    care: 'Dry clean only',
    origin: 'Handcrafted in London',
    description: 'The jasmine blooms in darkness, releasing its most intoxicating fragrance at night. Yasmin — a midnight navy abaya with the quiet confidence of deep waters — embodies this nocturnal grace. Its matte satin surface absorbs light rather than reflecting it: powerful in its subtlety.',
    details: 'Straight-cut with banded cuffs. Back kick pleat for ease of movement. Hidden inner pockets. Jersey-lined throughout.',
    seoDesc: 'Navy satin abaya by Safura London. Yasmin collection — midnight blue modest fashion with inner pockets. UK-made luxury.',
    badge: null,
    featured: false,
    sizes: [...SIZES],
  },
  {
    id: 5,
    slug: 'rania',
    name: 'Rania',
    arabic: 'رانيا',
    meaning: 'Queenly',
    tagline: 'Draped in sovereignty',
    price: 210,
    color: '#1A3020',
    accentColor: '#7FB88A',
    fabric: 'Silk-touch Nida',
    care: 'Dry clean only',
    origin: 'Handcrafted in London',
    description: 'Rania means queenly — and every stitch of this emerald abaya is designed to ensure you inhabit that truth. The Rania is not for the quiet moment; it is for the arrival. Deep forest green commands the room while the silk-touch Nida moves with regal ease.',
    details: 'Dramatic wide sleeves with cinched cuffs. Front slit from knee for elegant movement. Double-stitched seams for durability.',
    seoDesc: 'Emerald green luxury abaya by Safura London. Rania collection — silk-touch Nida in forest green. Modest fashion UK.',
    badge: null,
    featured: false,
    sizes: [...SIZES],
  },
  {
    id: 6,
    slug: 'aziza',
    name: 'Aziza',
    arabic: 'عزيزة',
    meaning: 'Precious',
    tagline: 'Gilded with intention',
    price: 245,
    color: '#C9A96E',
    accentColor: '#F5E6C8',
    fabric: 'Champagne jacquard with silk lining',
    care: 'Dry clean only',
    origin: 'Handcrafted in London',
    description: 'Aziza is our most opulent offering outside the Signature line. Woven from champagne jacquard with a subtle geometric pattern — inspired by Islamic tilework from Andalusia — it is modest fashion that carries centuries of artistry within its threads.',
    details: 'Fully silk-lined. Mandarin collar. Concealed gold-tone button placket. Statement cuff detail. Limited quantities per season.',
    seoDesc: 'Champagne jacquard luxury abaya by Safura London. Aziza collection — Islamic tilework-inspired modest fashion. Limited edition.',
    badge: 'Limited',
    featured: true,
    sizes: [...SIZES],
  },
  {
    id: 7,
    slug: 'samira',
    name: 'Samira',
    arabic: 'سميرة',
    meaning: 'Enchanting',
    tagline: 'Mystery made wearable',
    price: 220,
    color: '#261040',
    accentColor: '#A07EC8',
    fabric: 'Double-layered chiffon',
    care: 'Dry clean recommended',
    origin: 'Handcrafted in London',
    description: 'Samira draws you in. A deep aubergine purple with double-layered chiffon that creates an ethereal depth — as if the colour itself has dimension. The ultimate choice for formal occasions, evenings, and moments when ordinary simply will not do.',
    details: 'Two-layered chiffon creates volume and opaque coverage. Attached underdress included. Split bell sleeves. Floor-sweeping length.',
    seoDesc: 'Purple chiffon abaya by Safura London. Samira collection — aubergine modest fashion for formal occasions. UK luxury brand.',
    badge: null,
    featured: false,
    sizes: [...SIZES],
  },
  {
    id: 8,
    slug: 'nadia',
    name: 'Nadia',
    arabic: 'نادية',
    meaning: 'Tender',
    tagline: 'Softness as a statement',
    price: 155,
    color: '#3A1520',
    accentColor: '#E8B4B0',
    fabric: 'Rose-dusty crepe',
    care: 'Gentle machine wash, 30°C',
    origin: 'Handcrafted in London',
    description: 'Not all strength announces itself. Nadia — in its hushed blush rose — is strength that whispers. A beautifully understated abaya for the woman who knows that tenderness requires more courage than armour.',
    details: 'Relaxed fit with dropped shoulders. Pleated front panel. Machine-washable for everyday elegance. Generous sizing.',
    seoDesc: 'Blush rose abaya by Safura London. Nadia collection — machine-washable luxury modest fashion. Everyday elegance, UK-made.',
    badge: null,
    featured: false,
    sizes: [...SIZES],
  },
  {
    id: 9,
    slug: 'fatima',
    name: 'Fatima',
    arabic: 'فاطمة',
    meaning: 'Captivating',
    tagline: 'Warmth woven into form',
    price: 185,
    color: '#3A2510',
    accentColor: '#C8A46E',
    fabric: 'Camel wool-touch blend',
    care: 'Dry clean only',
    origin: 'Handcrafted in London',
    description: 'Fatima is named for warmth — and that warmth is woven into every fibre. A rich camel-toned abaya in a luxurious wool-touch blend, it is the perfect transitional piece: as fitting for autumn afternoons as for winter evenings. Soulful, grounded, beautiful.',
    details: 'Belted style with self-fabric sash. Patch pockets with gold-tone press-stud closure. Wool-touch blend provides warmth and structure.',
    seoDesc: 'Camel wool-touch abaya by Safura London. Fatima collection — autumn winter modest fashion UK. Warm luxury abaya.',
    badge: null,
    featured: false,
    sizes: [...SIZES],
  },
  {
    id: 10,
    slug: 'soraya',
    name: 'Soraya',
    arabic: 'ثريا',
    meaning: 'Starlit',
    tagline: 'The sky at its most still',
    price: 195,
    color: '#1E1E28',
    accentColor: '#C8C8DC',
    fabric: 'Dove grey satin-back crepe',
    care: 'Dry clean only',
    origin: 'Handcrafted in London',
    description: 'Soraya — named for the Pleiades star cluster — is silver-grey with a depth that shifts in different lights, much like the night sky. Its satin-back crepe offers two textures in one: a matte face and a luminous reverse, making every movement a conversation with light.',
    details: 'Reversible fabric with matte/satin contrast lining. Batwing sleeves. Elevated hem to ankle at front, floor-length at rear.',
    seoDesc: 'Grey luxury abaya by Safura London. Soraya collection — dove grey satin-back crepe abaya. Modest fashion London.',
    badge: null,
    featured: false,
    sizes: [...SIZES],
  },
  {
    id: 11,
    slug: 'layla',
    name: 'Layla',
    arabic: 'ليلى',
    meaning: 'Night',
    tagline: 'The night belongs to her',
    price: 235,
    color: '#080818',
    accentColor: '#4A6ABA',
    fabric: 'Midnight-blue duchess satin',
    care: 'Dry clean only',
    origin: 'Handcrafted in London',
    description: 'Layla is darkness given form — but it is not the absence of light. Look closely and you will find the deep midnight blue beneath: an abaya that reveals itself slowly, like night revealing stars. Duchess satin carries this depth with breathtaking weight and shine.',
    details: 'Structured duchess satin with shaped bodice seams. Dramatic cathedral-length sleeves. Embellished hem with tiny crystal beadwork. Truly a statement piece.',
    seoDesc: 'Midnight blue satin abaya by Safura London. Layla collection — crystal embellished luxury modest fashion. UK designer abaya.',
    badge: 'Signature',
    featured: false,
    sizes: [...SIZES],
  },
  {
    id: 12,
    slug: 'safura',
    name: 'Safura',
    arabic: 'صَفُورَة',
    meaning: 'Beautiful',
    tagline: 'Our name. Our promise.',
    price: 350,
    color: '#0A0A0A',
    accentColor: '#C9A96E',
    fabric: 'Italian pure silk with hand embroidery',
    care: 'Dry clean only',
    origin: 'Fully handcrafted in London',
    description: 'The Safura Signature Abaya is not a garment — it is an heirloom. Made entirely from Italian pure silk, each piece is hand-embroidered with our signature arabesque motif by a single artisan. No two are identical. This is the abaya you will pass to your daughter.',
    details: 'Pure Italian silk. Hand-embroidered arabesque collar and cuffs in real gold thread. Fully bespoke sizing available on request. Certificate of authenticity included. Allow 4–6 weeks for delivery.',
    seoDesc: 'Signature luxury silk abaya by Safura London. Hand-embroidered Italian silk, gold thread, unique piece. Premium UK modest fashion brand.',
    badge: 'Signature',
    featured: true,
    sizes: [...SIZES],
  },
];

/* Helper to get collection by slug */
function getProduct(slug) {
  return COLLECTIONS.find(c => c.slug === slug) || null;
}

/* Helper to get featured products */
function getFeaturedProducts() {
  return COLLECTIONS.filter(c => c.featured);
}

/* Abaya SVG silhouette (used in swatches) */
const ABAYA_SVG = `
<svg viewBox="0 0 180 320" xmlns="http://www.w3.org/2000/svg" fill="currentColor">
  <ellipse cx="90" cy="30" rx="22" ry="28"/>
  <path d="M 60 55 Q 55 70 50 85 L 10 160 L 25 165 L 55 105 L 55 320 L 125 320 L 125 105 L 155 165 L 170 160 L 130 85 Q 125 70 120 55 Z"/>
</svg>
`;

if (typeof module !== 'undefined') module.exports = { COLLECTIONS, SIZES, getProduct, getFeaturedProducts, ABAYA_SVG };
